---
title: "STAT 4610"
author: "Michael Ghattas"
date: "16/11/2022"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Chapter 6

```{r}
library(ISLR)
library(glmnet)
library(pls)
```


## Problem - 9

```{r}
attach(College)
```


### Part (a)

```{r}
set.seed(1)
train = sample(c(TRUE, FALSE), nrow(College), rep = TRUE)
test = (!train)

College.train = College[train, ]
College.test = College[test, ]
```


### Part (b)

```{r}
lm.fit = lm(Apps ~ ., data = College.train)
lm.pred = predict(lm.fit, College.test, type = "response")
mean((lm.pred - College.test$Apps)^2)
```
-> Linear model fit test-error = 984743.1


### Part (c)

```{r}
set.seed(1)

train.mat = model.matrix(Apps~., data = College.train)
test.mat = model.matrix(Apps~., data = College.test)

cv.out = cv.glmnet(train.mat, College.train$Apps, alpha = 0)
bestlam = cv.out$lambda.min
bestlam

ridge.mod = glmnet(train.mat, College.train$Apps, alpha = 0)
ridge.pred = predict(ridge.mod, s = bestlam, newx = test.mat)
mean((ridge.pred - College.test$Apps)^2)
```
-> Ridge regression fit test error with a cross-validation based lambda = 940970.9
-> Lower than linear model test error


### Part (d)

```{r}
set.seed(1)

cv.out2 = cv.glmnet(train.mat, College.train$Apps, alpha = 1)
bestlam2 = cv.out2$lambda.min
bestlam2

lasso.mod = glmnet(train.mat, College.train$Apps, alpha = 1)
lasso.pred = predict(lasso.mod,s = bestlam2, newx = test.mat)
mean((lasso.pred - College.test$Apps)^2)
```
-> Lasso model fit test error with a cross-validation based lambda = 993741.7
-> Higher than linear model and ridge regression test error